package vn.gas.thq.util

object ScreenId {
    const val SCREEN_LOGIN = "SCREEN_LOGIN"
//    const val SCREEN_CUSTOMER_CONTRACT_MENU = "SCREEN_CUSTOMER_CONTRACT_MENU"

    const val SCREEN_MAIN = "SCREEN_MAIN"
    const val SCREEN_RETAIL = "SCREEN_RETAIL"
    const val SCREEN_PHE_DUYET_GIA = "SCREEN_PHE_DUYET_GIA"
    const val SCREEN_QL_YC_DUYET_GIA_CONTAINER = "SCREEN_QL_YC_DUYET_GIA_CONTAINER"
}