package vn.gas.thq.util

object ScreenId {
    const val SCREEN_LOGIN = "SCREEN_LOGIN"
//    const val SCREEN_CUSTOMER_CONTRACT_MENU = "SCREEN_CUSTOMER_CONTRACT_MENU"

    const val SCREEN_MAIN = "SCREEN_MAIN"
    const val SCREEN_RETAIL_CONTAINER = "SCREEN_RETAIL_CONTAINER"
    const val SCREEN_RETAIL_STEP_1 = "SCREEN_RETAIL_STEP_1"
    const val SCREEN_RETAIL_STEP_2 = "SCREEN_RETAIL_STEP_2"
    const val SCREEN_PHE_DUYET_GIA = "SCREEN_PHE_DUYET_GIA"
    const val SCREEN_QL_YC_DUYET_GIA_CONTAINER = "SCREEN_QL_YC_DUYET_GIA_CONTAINER"
    const val SCREEN_THU_KHO = "SCREEN_THU_KHO"
    const val SCREEN_QLYC_CA_NHAN = "SCREEN_QLYC_CA_NHAN"
    const val SCREEN_LAP_YC_XUAT_KHO = "SCREEN_LAP_YC_XUAT_KHO"
}